// Directives
:toc:
:sectnums:

:hardbreaks:

= kafka-connect-custom-smt
Arijit Mazumdar<arijit.mazumdar@gmail.com>

== Overview
Refer https://docs.confluent.io/current/connect/transforms/index.html for Kafka Connect SMT.
This project attempts provides additional SMTs that are not readily available for use.

== Deployment

. Build
Download the project code and perform a maven build
+
----
mvn clean package
----
+
. Copy the resulting jar file to kafka connect `plugin.path` directory
. Restart connect.
Transformation classes defined in this project will be picked by the connect worker after restart.

== Usage
Sample Connector
+
---
{
  "name": "datagen-avro",
  "config": {
    "connector.class": "io.confluent.kafka.connect.datagen.DatagenConnector",
    "kafka.topic": "pageviews",
    "iterations": 20,
    "schema.filename": "/schema/pageviews_schema.avro",
    "schema.keyfield": "pageid",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter.schemas.enable": "true",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url":"http://schema-registry:8081",
    "tasks.max": "1",
    "transforms" : "fromJson",
    "transforms.fromJson.type" : "kafka.connect.smt.RedactPIIData$Value",
    "transforms.fromJson.fields" : "userid",
    "transforms.fromJson.replacement" : "**"
  }
}
---
Output
+
---
kcat -b localhost:9092 -C -t pageviews-string
{"viewtime":1,"userid":"**","pageid":"Page_2"}
{"viewtime":11,"userid":"**","pageid":"Page_18"}
{"viewtime":21,"userid":"**","pageid":"Page_2"}
{"viewtime":31,"userid":"**","pageid":"Page_36"}
{"viewtime":41,"userid":"**","pageid":"Page_45"}
---

